![](https://www.dii.uchile.cl/wp-content/uploads/2021/06/Magi%CC%81ster-en-Ciencia-de-Datos.png)

**MDS7202: Laboratorio de Programación Científica para Ciencia de Datos**

### 👨‍🏫👩‍🏫 Cuerpo Docente:

- Profesores: Diego Cortez, Gabriel Iturra
- Auxiliares: Melanie Peña, Valentina Rojas
- Ayudantes: Nicolás Cabello, Cristopher Urbina

### 👨‍💻👩‍💻 Estudiantes:
- Estudiante 1: Naomí Cautivo B.
- Estudiante 2: Máximo Flores Valenzuela

### Repositorio de GitHub: [maxfloresv/MDS7202](https://github.com/maxfloresv/MDS7202)

_Por favor, lean detalladamente las instrucciones de la tarea antes de empezar a escribir._

---

---

## 📖 Enunciado

<div align="center">
    <img src='https://github.com/MDS7202/MDS7202/blob/main/recursos/2025-01/proyecto/proyecto.png?raw=true' style="border-radius: 12px"> 
</div>

En el competitivo universo de las bebidas gaseosas, la empresa **SodAI Drinks 🥤** ha logrado destacarse por su creatividad, diversidad de productos y enfoque centrado en el cliente. Ofrece una extensa gama de bebidas carbonatadas que abarca distintos segmentos del mercado: desde productos premium en presentaciones sofisticadas, hasta gaseosas accesibles para el consumo masivo, disponibles en diversos tamaños y tipos de envases. 

La compañía opera en múltiples regiones y zonas, sirviendo a una variedad de puntos de venta que incluyen desde tiendas de conveniencia y minimarkets hasta el canal frío tradicional. Cada tipo de cliente tiene sus particularidades: algunos reciben entregas hasta 4 veces por semana, mientras que otros son visitados por la fuerza de ventas solo una vez semanalmente. Esta diversidad de perfiles representa tanto una oportunidad como un desafío comercial: ¿cómo saber qué productos tienen más chances de ser comprados por cada cliente en un momento dado?

Con el objetivo de aumentar la facturación de forma inteligente y mejorar la eficiencia de su estrategia de ventas, **SodAI Drinks** decide crear una nueva célula interna de innovación: el equipo **Deep Drinkers 🤖**, cuyo propósito es aplicar ciencia de datos para anticiparse a las necesidades del cliente y potenciar el negocio desde una perspectiva basada en información.

El corazón de esta iniciativa es el desarrollo de un sistema predictivo personalizado para cada cliente. Para ello, **Deep Drinkers** convoca a un equipo de Data Scientists y especialistas en *machine learning* con una misión clara: construir un modelo predictivo que, **cada semana, pueda estimar la probabilidad de compra de cada producto del portafolio para cada cliente activo**.

El modelo deberá tener en cuenta múltiples factores, incluyendo:
- **Tipo de cliente**, ej. "TIENDA DE CONVENIENCIA", "MINIMARKET".
- **Frecuencia de entregas y visitas**, indicadores del nivel de actividad comercial.
- **Ubicación geográfica** (por región y zona).
- **Preferencias históricas de consumo**, inferidas por patrones de compra anteriores.
- **Características del producto**, como marca, categoría, segmento, tipo de envase y tamaño

El objetivo final es que, **cada semana**, se genere una tabla de productos priorizados: para cada cliente, un listado de productos ordenado por su probabilidad estimada de compra. Esta información será enviada al equipo comercial, que podrá usarla en call center, para incrementar las chances de concretar ventas al ofrecer justo lo que el cliente probablemente quiere comprar.

Este proyecto representa un cambio de paradigma en la forma en que **SodAI Drinks** gestiona su fuerza de ventas: de un enfoque reactivo y generalista, a uno proactivo, basado en datos y profundamente personalizado. Así, la empresa no solo espera aumentar su rentabilidad, sino también construir relaciones más sólidas con sus clientes, ofreciéndoles recomendaciones más relevantes y oportunas.

Para lograr lo anterior, el equipo **Deep Drinkers** contará con los siguientes conjuntos de datos, junto a sus respectivos atributos:

- **Datos transaccionales** (`transacciones.parquet`): contiene el historial de compras realizadas por los clientes.
	- `customer_id`: identificador único del cliente que realizó la compra.
	- `product_id`: identificador único del producto comprado.
	- `purchase_date`: fecha en que se realizó la transacción.
	- `order_id`: identificar de la orden de su pedido.
	- `payment`	monto total pagado por la transacción.

- **Datos de clientes** (`clientes.parquet`): incluye las características de cada cliente.
	- `customer_id`: identificador único del cliente.
	- `region_id`: identificador de la región geográfica donde se encuentra el cliente.
	- `customer_type`: tipo de cliente según el canal comercial, por ejemplo, “TIENDA DE CONVENIENCIA”.
	- `Y`: coordenada geográfica de latitud.
	- `X`: coordenada geográfica de longitud.
	- `num_deliver_per_week`: cantidad de entregas semanales que recibe el cliente.
	- `num_visit_per_week`: frecuencia de visitas de la fuerza de ventas por semana.

- **Datos de productos** (`productos.parquet`): describe las características de los productos del portafolio.
	- `product_id`: identificador único del producto.
	- `brand`: marca comercial del producto.
	- `category`: categoría general del producto, como “BEBIDAS CARBONATADAS”.
	- `sub_category`: subcategoría dentro de la categoría principal, por ejemplo, “GASEOSAS”.
	- `segment`: segmento de mercado al que pertenece el producto, como “PREMIUM”.
	- `package`: tipo de envase del producto.
	- `size`: tamaño del producto en litros.

## 📚 Reglas

<center>
<img src="https://media1.tenor.com/m/0Qtv_cQ4ITsAAAAd/necohaus-grey-name.gif" width="450">



El proyecto consta de **dos entregas parciales** y una **entrega final** en donde la primera entrega la idea es poder reflejar lo aprendido durante la primera mitad del curso, que será sobre los contenidos relacionados a *machine learning*, la segunda será sobre los contenidos de la segunda mitad del curso relacionados a *MLOps* y por último la entrega final constará de dos partes, donde la primera será relacionada con experimentación sobre nuevos datasets que serán disponibilizados durante las últimas semanas del curso de manera incremental y una segunda parte que será el informe final escrito que deberá explicar el desarrollo del proyecto completo, como tambien los resultados y análisis de los experimentos realizados sobre los datasets incrementales. La idea es que todo el código esté desarrollado durante las primeras dos entregas y luego en la entrega final sólo se ejecute el código sobre nuevos conjuntos de datos.

La idea de generar el proyecto por etapas es poder aliviar la carga de trabajo en las últimas semanas del semestre donde sabemos que están muy cargado con entregas, pruebas y exámenes de otros ramos, y así garantizamos que habiendo la desarrollado las dos primeras entregas parciales, tendrán el grueso del proyecto listo para luego experimentar y documentar.

---
### **Fechas de entrega**
- **Entrega parcial 1**: 12 de Septiembre
- **Entrega parcial 2**: Por definir
- **Entrega final**: Por definir

---

### **Requisitos del proyecto**
- **Grupos**: Formar equipos de **2 personas**. No se aceptarán trabajos individuales o grupos con más integrantes.
- **Consultas**: Cualquier duda fuera del horario de clases debe ser planteada en el foro correspondiente. Los mensajes enviados al equipo docente serán respondidos únicamente por este medio. Por favor, revisen las respuestas anteriores en el foro antes de realizar nuevas consultas.
- **Plagio**: La copia o reutilización no autorizada de trabajos de otros grupos está **estrictamente prohibida**. El incumplimiento de esta norma implicará la anulación inmediata del proyecto y una posible sanción académica.
- **Material permitido**: Pueden usar cualquier material del curso, ya sea notas, lecturas, códigos, o referencias proporcionadas por los docentes, que consideren útil para el desarrollo del proyecto.

---

### **Entregables y etapas**

#### **1. Entrega Parcial 1**  
- Dispondrán de los archivos de datos **productos.parquet**, **clientes.parquet** y **transacciones.parquet** para el modelamiento inicial.  
- Utilizarán estos archivos para desarrollar lo solicitado para la entrega 1. 
- En esta etapa, se espera que apliquen todos los conocimientos aprendidos durante la primera parte del curso relacionados con *machine learning*.
- **Informe**: No se exige un avance del informe en esta etapa, sólo un notebook con su desarrollo actual, pero se **recomienda comenzar** a redactar el informe final en paralelo para disminuir la carga académica en las etapas posteriores.  

#### **2. Entrega Parcial 2**  
- En esta entrega, deberán aplicar los conocimientos aprendidos durante la segunda mitad del curso sobre *MLOps*  
- Se espera que implementen estos conocimientos para desplegar su modelo elegido en la primera entrega y crear *pipelines* automatizados que simulen un entorno productivo.
- **Informe**: similar a la primera etapa, no se exige un avance del informe, pero se **recomienda avanzar con su redacción** para evitar una acumulación de trabajo en la etapa final.  

#### **3. Entrega Final**  
- En la entrega final, deberán realizar dos etapas:
	- La primera etapa es sobre experimentación utilizando datasets incrementales que se irán disponibilizando de manera parcial, para que vayan generando predicciones con su modelo ya desplegado. El objetivo de esta etapa es poder testear su solución *end-to-end* y que vayan analizando los resultados obtenidos a medida que se van agregando más datos.
	- La segunda etapa consiste en redactar un informe final que deberá explicar el desarrollo completo de tu proyecto y un análisis profundo de sus resultados de experimentación. Este informe debera incluir a lo menos las siguientes secciones:
		- Análisis exploratorio de datos  
		- Metodología aplicada  
		- Selección y entrenamiento de modelos  
		- Evaluación de resultados  
		- Optimización de modelos
		- Interpretabilidad
		- Re-entrenamiento
		- Tracking con MLFlow
		- Creación de la aplicación web con Gradio y FastAPI

Es **altamente recomendable** ir redactando el informe en paralelo al desarrollo de los modelos para garantizar que toda la información relevante quede documentada adecuadamente.  

### Nota Final

La calificación final de su proyecto se calculará utilizando la siguiente ponderación: 

$$Nota Final = 0.30 * EntregaParcial1 + 0.40 * EntregaParcial2 + 0.30 * EntregaFinal$$

---

### **Instrucciones importantes**

1. **Formato del informe**:  
   - El informe debe estar integrado dentro de un **Jupyter Notebook**. No es necesario subirlo a una plataforma externa, pero debe cumplir con los siguientes requisitos:  
     - Estructura clara y ordenada.  
     - Código acompañado de explicaciones detalladas.  
     - Resultados presentados de forma visual y analítica.  

2. **Descuento por informes deficientes**:  
   - Cualquier sección del informe que no tenga una explicación adecuada o no respete el formato será penalizada con un descuento en la nota. Esto incluye código sin comentarios o análisis que no sean coherentes con los resultados presentados.
   - Comentarios sin formatear de ChatGPT o herramientas similares serán penalizados (e.g: "Inserta tu modelo acá", etc.)

# 📬 Entrega Parcial 1 (30% del Proyecto)

### 📪 Fecha de Entrega: 12 de Septiembre

## 📌 Abstract [0.25 puntos]

<center>
<img src="https://i.redd.it/h5ptnsyabqvd1.gif" width="400" height="300">

En esta sección, deben redactar un Abstract claro y conciso para su proyecto. El Abstract debe responder a las siguientes preguntas clave:

- **Descripción del problema**: ¿Cuál es el objetivo del proyecto? ¿Qué se intenta predecir o analizar?
- **Datos de entrada**: ¿Qué datos tienen disponibles? ¿Cuáles son sus principales características?
- **Métrica de evaluación**: ¿Cómo medirán el desempeño de sus modelos? Expliquen por qué eligieron esta métrica basándose en el análisis exploratorio de los datos.
- **Modelos y transformaciones**: ¿Qué modelos utilizarán y por qué? ¿Qué transformaciones o preprocesamientos aplicaron a los datos?
- **Resultados generales**: ¿El modelo final cumplió con los objetivos del proyecto? ¿Cuáles fueron las conclusiones más importantes?

**Importante**: Escriban esto despues de haber resuelto el resto de la tarea.

> [Escriba aquí su Abstract]

## 📌 Pre-procesamiento [0.5 puntos]

<center>
<img src="https://media0.giphy.com/media/10zsjaH4g0GgmY/giphy.gif?cid=6c09b9523xtlunksc9amikw09zk1bmiqwjqnt70ae82rk877&ep=v1_gifs_search&rid=giphy.gif&ct=g" width="400" height="300">

Tal como en muchos otros problemas de negocio, los datos probablemente deben ser pre procesados antes de aplicar cualquier técnica de analítica. Bajo esa premisa, en esta sección deben desarrollar código que les permita **preparar los datos** de tal forma que les permita resolver el problema planteado. Para esto, pueden aplicar procesamientos como:

- Transformaciones de tipo de dato (str, int, etc)
- Cruce de información
- Eliminación de duplicados
- Filtros de fila y/o columnas

*Hint: ¿Qué forma debería tener la data para resolver un problema de aprendizaje supervisado?*

Todo proceso llevado a cabo debe estar bien documentado y justificado en el informe, explicando el por qué se decidió realizar en funcion de los datos presentados y los objetivos planteados del proyecto.

### Desarrollo

Primero, se procederá a instalar la librería `fastparquet` que permite cargar los datos en formato `.parquet`.

In [25]:
%%capture

%pip install fastparquet

Posteriormente, se cargarán los datos usando el motor que suministra la librería antes mencionada.

In [26]:
import pandas as pd

customers = pd.read_parquet(
    'data/clientes.parquet', 
    engine='fastparquet'
)

transactions = pd.read_parquet(
    'data/transacciones.parquet', 
    engine='fastparquet'
)

products = pd.read_parquet(
    'data/productos.parquet', 
    engine='fastparquet'
)

Y se revisarán las primeras $5$ observaciones de cada _dataset_ usando la función `head()` de la librería Pandas.

In [27]:
customers.head()

,customer_id,region_id,zone_id,customer_type,Y,X,num_deliver_per_week,num_visit_per_week
10705,256017,80,5148,ABARROTES,-46.474800,-108.045140,1,1
10706,255780,80,5148,ABARROTES,-46.520282,-107.961052,1,1
10707,254655,80,5148,ABARROTES,-46.537640,-107.909280,1,1
10708,254445,80,5148,ABARROTES,-46.543526,-107.917954,2,1
10709,254403,80,5148,ABARROTES,-46.540856,-107.905792,3,1

Se inspeccionarán los valores únicos de las columnas `region_id`, `zone_id`, `customer_type`, `num_visit_per_week`.

In [28]:
print(customers['region_id'].unique())
print(customers['zone_id'].unique())
print(customers['customer_type'].unique())
print(customers['num_visit_per_week'].unique())

[80]
[5148]
['ABARROTES' 'MAYORISTA' 'TIENDA DE CONVENIENCIA' 'CANAL FRIO'
 'RESTAURANT' 'SUPERMERCADO' 'MINIMARKET']
[1]

Las variables `region_id`, `zone_id` y `num_visit_per_week` no aportan variabilidad a los datos, dado que sólo tienen un valor fijo. Quedará documentado que `region_id` es $80$, `zone_id` es $5.148$ y `num_visit_per_week` es $1$, para todos los clientes.

In [29]:
customers.drop(
  columns=['region_id', 'zone_id', 'num_visit_per_week'],
  inplace=True
)
customers.head()

       customer_id customer_type          Y           X  num_deliver_per_week
10705       256017     ABARROTES -46.474800 -108.045140                     1
10706       255780     ABARROTES -46.520282 -107.961052                     1
10707       254655     ABARROTES -46.537640 -107.909280                     1
10708       254445     ABARROTES -46.543526 -107.917954                     2
10709       254403     ABARROTES -46.540856 -107.905792                     3

In [30]:
transactions.head()

     customer_id  product_id  order_id purchase_date     items
124        61353       61364    411145    2024-04-27 -0.333333
127        61899        1370    411156    2024-04-27  3.666667
344       154077       30500    417911    2024-04-29  2.333333
349       164337       56714    418100    2024-04-29 -2.333333
354       172056       61672    407162    2024-04-26  1.000000

In [31]:
products.head()

,product_id,brand,category,sub_category,segment,package,size
0,34092,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
1,57290,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
2,56714,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
3,296616,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
4,60854,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.25

Con el objetivo de conocer los tipos de cada columna de los _datasets_, se usará `dtypes`.

In [32]:
print(customers.dtypes)
print("----------------")
print(transactions.dtypes)
print("----------------")
print(products.dtypes)

customer_id               int64
customer_type            object
Y                       float64
X                       float64
num_deliver_per_week      int64
dtype: object
----------------
customer_id               int64
product_id                int64
order_id                  int64
purchase_date    datetime64[ns]
items                   float64
dtype: object
----------------
product_id        int64
brand            object
category         object
sub_category     object
segment          object
package          object
size            float64
dtype: object

Con esto, se puede confirmar que los tipos de datos están bien asignados, pues corresponden con los vistos en la previsualización exploratoria generada por `head()`.

A continuación, se buscará la **llave candidata**, es decir, la superllave minimal. Para las tablas `customers` y `products`, es intuitivo que estas llaves corresponden a `customer_id` y `product_id` respectivamente. Esto se puede confirmar con las siguientes condiciones _booleanas_.

Para `customers`:

In [33]:
customers['customer_id'].nunique() == customers.shape[0]

True

Y para `products`:

In [34]:
products['product_id'].nunique() == products.shape[0]

True

Sin embargo, para `transactions` el tema es más difícil: ya no es intiutivo decir que `order_id` es una superllave, pues pueden haber múltiples transacciones que se generaron en una orden. Esto se confirma en la siguiente celda de código.

In [35]:
transactions['order_id'].nunique() == transactions.shape[0]

False

Acá, es más intuitivo que la llave candidata sea la tupla $($`product_id`$,$ `order_id`$)$, dado que las otras $2$-combinaciones posibles generan repeticiones: `order_id` con `customer_id` se puede repetir en el caso de que un cliente compre varios productos en una misma orden, y `customer_id` con `product_id` se puede repetir cuando un cliente compra el mismo producto en distintas órdenes.

A continuación para confirmar su naturaleza de llave candidata, se corroborará si existen duplicados de la combinación de `product_id` y `order_id`.

In [36]:
key_cols = ["product_id", "order_id"]

In [37]:
duplicated = (
    transactions.groupby(key_cols)
        .size()
        .reset_index(name="count")
)
duplicated = duplicated[duplicated['count'] > 1]
duplicated = duplicated.sort_values("count", ascending=False)
duplicated.head(10)

        product_id  order_id  count
99652        11262   1210079      7
131667       35732   1210079      5
196179       56714   1210079      5
22109         1304   1210079      5
87198        11262    586399      5
181499       56714    251114      5
77188        11262     79386      5
170431       50718    927180      5
160567       50716    249289      5
781            124    249289      5

Dada la existencia de duplicados para la tupla candidata, se procederá a revisar el caso particular de la fila que tiene más duplicados.

In [38]:
transactions[
    (transactions["product_id"] == 11262) 
    & (transactions["order_id"] == 1210079)
]

         customer_id  product_id  order_id purchase_date     items
188414        186990       11262   1210079    2024-12-22  7.000000
3609374       186990       11262   1210079    2024-12-22  7.000000
3617516       186990       11262   1210079    2024-12-22 -1.000000
3622881       186990       11262   1210079    2024-12-22 -6.333333
3629248       186990       11262   1210079    2024-12-22  1.666667
3883806       186990       11262   1210079    2024-12-22 -6.333333
3905258       186990       11262   1210079    2024-12-22  7.000000

Al analizar el caso particular, se puede ver que existen filas donde los ítems son negativos, contrastando con el hecho de que el número de ítems debe ser positivo intuitivamente.

A continuación, se calcularán las observaciones que tienen ítems con cantidad negativa y son únicos, es decir, no hay otra observación con la misma _pseudollave candidata_ que tenga otra cantidad de ítems.

In [39]:
neg_items_projection = transactions[
    transactions['items'] < 0
][['product_id', 'order_id']]

dupes_projection = duplicated[['product_id', 'order_id']]

neg_items_rows = neg_items_projection.shape[0]

set_neg = set(neg_items_projection.apply(tuple, axis=1))
set_dupes = set(dupes_projection.apply(tuple, axis=1))

diff_set = set_neg - set_dupes
diff_set

{(1304, 190712),
 (1370, 190712),
 (1372, 190712),
 (30500, 1141245),
 (35846, 190712),
 (54290, 365855),
 (61280, 1135948)}

In [40]:
for dtuple in diff_set:
    product_id, order_id = dtuple
    unique_neg = transactions[
        (transactions['product_id'] == product_id)
        & (transactions['order_id'] == order_id)
    ]
    print(unique_neg)
    print("-" * 10)

         customer_id  product_id  order_id purchase_date  items
2162431       156057       30500   1141245    2024-12-06   -1.0
----------
         customer_id  product_id  order_id purchase_date      items
7093162       162810       61280   1135948    2024-12-05 -46.333333
----------
         customer_id  product_id  order_id purchase_date     items
4654028       204189        1304    190712    2024-02-22 -2.333333
----------
         customer_id  product_id  order_id purchase_date     items
4658765       204189        1370    190712    2024-02-22 -2.333333
----------
         customer_id  product_id  order_id purchase_date     items
4657476       204189        1372    190712    2024-02-22 -0.333333
----------
         customer_id  product_id  order_id purchase_date     items
7190282       210615       54290    365855    2024-04-12 -0.333333
----------
         customer_id  product_id  order_id purchase_date     items
4631011       204189       35846    190712    2024-02-22 -0.333333
----------

Tomando una fila $\vec{x} \in \mathbb{R}^d$ que tiene una combinación de valores $(x_\texttt{product\_id}, x_\texttt{order\_id})$ única, entonces el porcentaje de filas con ítems menores que $0$ donde **no hay otra observación asociada a la misma combinación** se calcula como $\lvert N \setminus D \rvert / \lvert N \rvert$, donde $N$ es el conjunto de observaciones $\vec{x} \in \mathbb{R}^d$ tales que $x_\texttt{items} < 0$, y $D$ es el conjunto de observaciones $\vec{x} \in \mathbb{R}^d$ tales que $\exists \vec{x}' \in \mathbb{R}^d$, $\vec{x} \neq \vec{x}'$, $x_K = x'_K$, con $K$ el subconjunto de variables asociadas a la llave candidata $(x_\texttt{product\_id}, x_\texttt{order\_id})$.

En la siguiente celda de código, se puede verificar el siguiente resultado:
$$
    \frac{\lvert N \setminus D \rvert}{\lvert N \rvert} \approx 0\text{,}08\, \%
$$

In [41]:
print(f'{(len(diff_set) / neg_items_rows) * 100:.2f} %')

0.08 %

Por otro lado, la proporción de observaciones con ítems negativos con respecto al total de transacciones se puede definir como $\lvert N \rvert / \lvert T \rvert$, donde $T$ es el conjunto de transacciones. En la siguiente celda de código, se puede verificar que esa división da como resultado $3\text{,}29\,\%$, es decir, un poco más del $3\,\%$ de las observaciones tienen ítems negativos.

In [42]:
print(f'{(neg_items_rows / transactions.shape[0]) * 100:.2f} %')

3.29 %

Las observaciones que pertenecen al conjunto $N \setminus D$ se van a considerar como pedidos fallidos, dado que no existe otra observación con una combinación $(x_\texttt{product\_id}, x_\texttt{order\_id})$ asociada a la _pseudollave candidata_ (_pseudo_ porque se vio que hay identificadores repetidos), entonces no hay información sobre cuántos ítems se llevaron realmente, pues debiese ser una cantidad mayor que $0$, como ocurre en las observaciones que viven en $N \cap D$.

In [43]:
mask = (
    transactions[['product_id', 'order_id']]
        .apply(tuple, axis=1)
        .isin(diff_set)
)
print("Filas a eliminar:", transactions[mask].shape[0])
transactions = transactions[~mask]

Filas a eliminar: 7

El único conjunto de observaciones con ítems negativos que queda por analizar es $N \cap D$, dado que:
$$
    N = (N \setminus D) \cup (N \cap D); \quad (N \setminus D) \cap (N \cap D) = \emptyset
$$
Para reducir las observaciones con _pseudollave candidata_ duplicada, se usará el criterio del máximo de las modas, es decir:
$$
        C_{p,q} =  \{\vec{x} \in \mathbb{R}^d \mid x_\texttt{product\_id} = p \land x_\texttt{order\_id} = q \} \mapsto \{\vec{x}'\} \text{ tal que } x'_\texttt{items} = \max \text{moda}(C^\texttt{items}_{p, q})
$$
donde $C^\texttt{items}_{p,q}$ es el multiconjunto $\{\pi_\texttt{items}(\vec{x}) \mid \vec{x} \in C_{p,q} \}$, y $\pi_{(\cdot)}$ es la proyección de un vector a una de sus características. Es importante notar que la moda pueden ser varios valores, por eso se toma el más grande de ellos.

Esto se justifica con que en una orden mal ingresada, como es el caso de estas observaciones duplicadas con ítems negativos, el valor que más se repite tiende a ser el correcto.

In [44]:
prev_rows = transactions.shape[0]
mode_max = (
    transactions
        .groupby(['product_id', 'order_id'])['items']
        .transform(lambda x: x.mode().max())
)
mode_max

124        1.000000
127        3.666667
344        2.333333
349        3.000000
354        1.000000
             ...
7712445    1.666667
7712469    3.666667
7712538    3.000000
7712547    1.000000
7712548    3.666667
Name: items, Length: 254929, dtype: float64

In [45]:
transactions = transactions[
    transactions['items'] == mode_max
]
transactions.drop_duplicates(inplace=True)
print(f"Se eliminaron {prev_rows - transactions.shape[0]} filas")

Se eliminaron 11598 filas

A continuación, se verificará que no queden transacciones con una cantidad de ítems negativa:

In [46]:
transactions[transactions['items'] < 0]

Empty DataFrame
Columns: [customer_id, product_id, order_id, purchase_date, items]
Index: []

A continuación, se eliminarán los _customers_ que no tienen ninguna transacción, y los productos que nunca se han comprado, para limpiar el _dataset_ de entradas irrelevantes.

In [ ]:
def get_filtered_customers(min_transactions: int = 1) -> pd.DataFrame:
  """
  Get customers with at least a minimum number of transactions.

  Parameters
  ----------
  min_transactions : int
    Minimum number of transactions a customer must have to be included.

  Returns
  -------
  pd.DataFrame
    Filtered customers DataFrame.
  """
  counts = transactions['customer_id'].value_counts()
  filtered_customers_id = counts[counts >= min_transactions].index
  return customers[customers['customer_id'].isin(filtered_customers_id)]

def get_filtered_products(min_transactions: int = 1) -> pd.DataFrame:
  """
  Get products bought at least a minimum number of times.

  Parameters
  ----------
  min_transactions : int
      Minimum number of transactions a product must have to be included.

  Returns
  -------
  pd.DataFrame
      Filtered products DataFrame.
  """
  counts = transactions['product_id'].value_counts()
  filtered_products_id = counts[counts >= min_transactions].index
  return products[products['product_id'].isin(filtered_products_id)]

print("Antigua shape de clientes:", customers.shape[0])
filtered_customers = get_filtered_customers()
customers = customers[
  customers['customer_id']
    .isin(
      filtered_customers['customer_id']
    )
]
print("Nueva shape de clientes:", customers.shape[0])
print("Antigua shape de productos:", products.shape[0])
filtered_products = get_filtered_products()
products = products[
  products['product_id']
    .isin(
      filtered_products['product_id']
    )
]
print("Nueva shape de productos:", products.shape[0])

Para unificar las tablas, se debe considerar el objetivo, que es predecir cada semana la probabilidad de que cada cliente compre cada producto del catálogo. Entonces, la tabla final debiese contener observaciones donde haya un cliente asociado a los $N$ productos, todas las semanas del año enumeradas con la función `isocalendar()`, y si compró o no dicha semana.

In [ ]:
transactions['week'] = (
    transactions['purchase_date'].dt.isocalendar().week
)

customer_ids = customers['customer_id'].unique()
product_ids = products['product_id'].unique()
weeks = transactions['week'].unique()

base = pd.MultiIndex.from_product(
    [customer_ids, product_ids, weeks],
    names=['customer_id', 'product_id', 'week']
).to_frame(index=False)

print(f"Observaciones del cruce:", base.shape[0])
base.head()

Observaciones del nuevo DataFrame: 79221948

   customer_id  product_id  week
0       256017       34092    17
1       256017       34092    18
2       256017       34092     5
3       256017       34092     4
4       256017       34092     2

In [54]:
# Esto indica que compró en una semana específica
weekly_trx = (
    transactions.groupby(['customer_id', 'product_id', 'week'])
        .agg({'items': 'sum'})
        .reset_index()
)

df = base.merge(
    weekly_trx[['customer_id', 'product_id', 'week', 'items']],
    on=['customer_id', 'product_id', 'week'],
    how='left'
)

df.head()

   customer_id  product_id  week  items
0       250020       34092    17    NaN
1       250020       34092    18    NaN
2       250020       34092     5    NaN
3       250020       34092     4    NaN
4       250020       34092     2    NaN

Considerando esta fusión, se define la siguiente variable objetivo (`label`):
$$
    y_{i,j,t} = \begin{cases}
        1 & \text{si el cliente } i \text{ compró el producto } j \text{ en la semana } t \\
        0 & \text{si no}
    \end{cases}
$$

donde $i$ se extrae de `customer_id`, $j$ de `product_id` y $t$ de `week`.

Esta variable se buscará predecir mediante métodos de _Machine Learning_ supervisado que estimen la probabilidad de la siguiente manera:
$$
    \hat{y}_{i,j,t} = \mathbb{P}(y_{i,j,t} = 1 \mid \vec{x}_{i,j,t})
$$
donde $\vec{x}_{i,j,t}$ es el vector de características asociado a la observación $(i,j,t)$, es decir, la probabilidad que el cliente $i$ compre el producto $j$ en la semana $t$ dadas sus características como cliente.

In [50]:
df['items'] = df['items'].fillna(0)
df['label'] = (df['items'] > 0).astype(int)
df.drop(columns=['items'], inplace=True)
df.head()

   customer_id  product_id  week  label
0       250020       34092    17      0
1       250020       34092    18      0
2       250020       34092     5      0
3       250020       34092     4      0
4       250020       34092     2      0

El remanente es generar los cruces para obtener los datos originales. Se hará esto con `customers` y `products`, que aportan información valiosa.

In [51]:
df = df.merge(
  customers,
  on='customer_id',
  how='left'
)
df.head()

,customer_id,product_id,week,label,customer_type,Y,X,num_deliver_per_week
0,250020,34092,17,0,ABARROTES,-46.522996,-108.237112,3
1,250020,34092,18,0,ABARROTES,-46.522996,-108.237112,3
2,250020,34092,5,0,ABARROTES,-46.522996,-108.237112,3
3,250020,34092,4,0,ABARROTES,-46.522996,-108.237112,3
4,250020,34092,2,0,ABARROTES,-46.522996,-108.237112,3

In [52]:
df = df.merge(
  products,
  on='product_id',
  how='left'
)

df.head()

KeyboardInterrupt:

Estos datos se pasarán a formato `.parquet`, para guardarlos eficientemente.

In [ ]:
df.to_parquet(
  'data/processed_data.parquet', 
  engine='fastparquet', 
  index=False
)

## 📌 EDA [0.5 puntos]

<center>
<img src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExbHZ6aGdkd21tYTI3cW8zYWhyYW5wdGlyb2s3MmRzeTV0dzQ1NWlueiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3k1hJubTtOAKPKx4k3/giphy.gif" width="400" height="200">

En esta sección, se debe realizar un análisis exploratorio de los datos para comprender su estructura, detectar posibles problemas y obtener información relevante para el entrenamiento de los modelos. La idea es que puedan detectar **patrones en los datos** que les permitan resolver el problema con mayor facilidad.

Se deben responder preguntas a partir de lo que puedan visualizar/obtener, por ejemplo:

- Clientes y productos

    - ¿Cuántos clientes únicos hay en el dataset?

    - ¿Cuántos productos únicos se encuentran en los datos?

- Periodo y frecuencia

    - ¿De qué periodo es la información disponible?

    - ¿Cuál es la frecuencia de los registros (diaria, semanal, mensual, etc.)?

- Calidad de los datos

    - ¿Existen valores nulos en el dataset? ¿Cuántos? ¿Cómo se pueden tratar?

    - ¿Hay datos raros, como cantidades negativas o inconsistencias? Genere tests de validación para identificar estos problemas.

- Patrones de compra

    - ¿Cuántos productos compra en promedio cada cliente semana a semana?

    - ¿Cuántas transacciones ha realizado cada cliente?

    - ¿Cuál es el periodo de recompra promedio de cada SKU?

Primero, se descargará el _dataset_ ya procesado del punto anterior.

In [ ]:
%%capture

!pip install gdown

Requirement already satisfied: gdown in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from gdown) (4.14.2)
Requirement already satisfied: filelock in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from gdown) (3.19.1)
Requirement already satisfied: requests[socks] in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from gdown) (2.32.5)
Requirement already satisfied: tqdm in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from gdown) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from beautifulsoup4->gdown) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from requests[socks]->gdown) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from requests[socks]->gdown) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from requests[socks]->gdown) (2025.8.3)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from requests[socks]->gdown) (1.7.1)
Requirement already satisfied: colorama in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from tqdm->gdown) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
%%capture

!gdown "https://drive.google.com/uc?id=1UqAFHXtD5M8OJ4xBR5ngNLOjd6sqVSye" -O data/processed_data.parquet

In [ ]:
processed_df = pd.read_parquet(
    'data/processed_data.parquet',
    engine='fastparquet')

In [ ]:
processed_df.head()

,customer_id,product_id,week,label,customer_type,Y,X,num_deliver_per_week,brand,category,sub_category,segment,package,size
0,250020,34092,17,0,ABARROTES,-46.522996,-108.237112,3,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
1,250020,34092,18,0,ABARROTES,-46.522996,-108.237112,3,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
2,250020,34092,5,0,ABARROTES,-46.522996,-108.237112,3,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
3,250020,34092,4,0,ABARROTES,-46.522996,-108.237112,3,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
4,250020,34092,2,0,ABARROTES,-46.522996,-108.237112,3,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66

In [ ]:
processed_df.dtypes

customer_id               int64
product_id                int64
week                     UInt32
label                     int32
customer_type            object
Y                       float64
X                       float64
num_deliver_per_week      int64
brand                    object
category                 object
sub_category             object
segment                  object
package                  object
size                    float64
dtype: object

In [ ]:
processed_df['week'] = processed_df['week'].astype('int64')
processed_df['label'] = processed_df['label'].astype('int64')

A continuación se verificará la cantidad de clientes únicos existentes en el _dataframe_ ya preprocesado. En este caso, basta con un `.nunique()`, el cual retorna la cantidad de valores únicos de la fila `customer_id`, esta es llave candidata por lo visto en el apartado anterior, por tanto este comando es suficiente para retornar la cantidad de clientes únicos.

In [ ]:
clients= processed_df['customer_id'].nunique()
print(f'Número de clientes: {clients}')

Número de clientes: 1124

In [ ]:
fig = px.bar(x=["Customers"], y=[clients],
             text=[clients],
             title="Número total de customers únicos")
fig.update_traces(textposition="outside")
fig.update_layout(yaxis_title="Cantidad")
fig.show()

Con un mecanismo similar, se contará la cantidad de productos únicos en los datos, cabe a destacar que tanto `customer_id` como `product_id` son considerados como llave candidata, por tanto al utilizar `nunique()`, estamos capturando los productos sin problemas.

In [ ]:
n_products= processed_df['product_id'].nunique()
print(f'Número de productos: {n_products}')

Número de productos: 971

In [ ]:
fig = px.bar(x=["Productos"], y=[n_products],
             text=[n_products],
             title="Número total de productos únicos")
fig.update_traces(textposition="outside")
fig.update_layout(yaxis_title="Cantidad")
fig.show()

## 📌 Holdout [0.25 puntos]

Para evaluar correctamente el modelo y garantizar su capacidad de generalización, se deben dividir los datos en tres conjuntos: 
- `Entrenamiento` : Para ajustar los parámetros.
- `Validación`: Para optimizar hiperparámetros y seleccionar el mejor modelo.
- `Prueba` : Para evaluar el rendimiento final en datos no vistos.

👀 **Hint**: *Recuerde que los datos tienen una temporalidad que debe considerarse al momento de separarlos, para evitar fugas de información. Es importante justificar la estrategia de partición elegida y visualizar la distribución temporal de los conjuntos generados*

In [ ]:
# Desarrolle aquí su código

## 📌 Feature Engineering [0.5 puntos]

<center>
<img src="https://i.imgur.com/CmXZSSC.gif" width="300" height="200">

En esta sección, se deben construir pipelines para automatizar el preprocesamiento de los datos, lo cual garantizará que el flujo de trabajo sea reproducible y eficiente para esta entrega y las futuras. El objetivo es aplicar una serie de transformaciones en un orden definido para asegurar que los datos estén listos para los modelos a entrenar. El pipeline final debe incluir las técnicas de pre-procesamiento que se deben aplicar a los distintos datos (según lo que consideren necesario para el problema). Por ejemplo:

- **Imputación de valores nulos**: Manejo de datos faltantes mediante estrategias adecuadas (media, mediana, moda, interpolación, etc.). 

- **Transformaciones personalizadas**: Uso de ColumnTransformer para aplicar diferentes transformaciones a columnas específicas.

- **Codificación de variables categóricas**: Convertir datos categóricos a un formato numérico adecuado (One-Hot Encoding, Label Encoding, etc.).

- **Discretización de variables**: Conversión de variables numéricas continuas en categorías si son relevantes para el desempeño del modelo a entrenar.

- **Estandarización o normalización** : Ajustar la escala de los datos para mejorar el rendimiento de los algoritmos sensibles a la magnitud de las variables.

- **Eliminación o transformación de valores atípicos**: Identificar y tratar con datos outliers para mejorar la robustez del modelo.

- **Nuevas características** : Creación de variables adicionales que puedan aportar información relevante al modelo.

Cada una de estas transformaciones debe ser justificada en función de su relevancia para el problema y los datos, y es importante evaluar su impacto en el rendimiento del modelo. Además, el pipeline debe ser flexible y modular para poder probar diferentes configuraciones de preprocesamiento.

In [ ]:
# Desarrolle aquí su código

## 📌 Baseline [0.25 puntos]

<center>
<img src="https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExN3lzeGFqZmU3NzJrZHllNjRmaHVzczJpZ29rdHdlMzVpZnQwNXo1diZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/qAtZM2gvjWhPjmclZE/giphy.gif" width="300" height="200">

En esta sección se debe construir el modelo más sencillo posible que pueda resolver el problema planteado, conocido como **Modelo baseline**. Su propósito es servir como referencia para comparar el rendimiento de los modelos más avanzados desarrollados en etapas posteriores.  

Pasos requeridos:  
- Implemente, entrene y evalúe un modelo básico utilizando un pipeline.  
- Asegúrese de incluir en el pipeline las transformaciones del preprocesamiento realizadas previamente junto con un clasificador básico.  
- Evalúe el modelo y presente el informe de métricas utilizando **`classification_report`**.  

Documente claramente cómo se creó el modelo, las decisiones tomadas y los resultados obtenidos. Este modelo será la base comparativa en las secciones posteriores.

In [ ]:
# Desarrolle aquí su código

## 📌 Elección de modelo [0.75 puntos]

En esta sección deben escoger un modelo que se adapte a las necesidades del negocio. Para esto, pruebe al menos 3 modelos y desarrolle los siguientes aspectos para cada uno:

- **Estructura y diferencias entre los modelos**: Explicar brevemente cada uno y sus hipérparámetros de mayor importancia.
- **Clasificadores recomendados**:
  - `LogisticRegression`
  - `KNeighborsClassifier`
  - `DecisionTreeClassifier`
  - `SVC`
  - `RandomForestClassifier`
  - `LightGBMClassifier` (del paquete `lightgbm`)
  - `XGBClassifier` (del paquete `xgboost`)
  - Otro (según lo que se estime adecuado)
  
- **Evaluación de resultados**: Se utilizará el **`classification_report`** para evaluar el rendimiento de cada modelo, destacando métricas clave como precisión, recall y F1-score. **Importante: No optimicen hiperparámetros, la idea es hacer una selección rápida del modelo.**

**Nota:** Pueden ocupar mas de 1 **instancia** de modelo para resolver el problema (e.g: (modelo_1, grupo_1), (modelo_2, grupo_2), ...).
  
A continuación, se deben responder las siguientes preguntas para evaluar el rendimiento de los modelos entrenados:

1. ¿Hay algún clasificador que supere al modelo baseline?  
2. ¿Cuál es el mejor clasificador entrenado y por qué?  
3. ¿Qué factores hacen que el mejor clasificador sea superior a los otros?  
4. En términos de `tiempo de entrenamiento`, ¿Qué modelo considera más adecuado para experimentar con grillas de optimización?

In [ ]:
# Desarrolle aquí su código

## 📌 Optimización de Hiperparámetros [1.0 puntos]

<center>
<img src="https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExcXJkNzdhYjlneHplaGpsbnVkdzh5dnY3Y2VyaTIzamszdGR1czJ2diZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/2rqEdFfkMzXmo/giphy.gif" width="300" height="200">

A partir de su análisis anterior, se debe proceder a optimizar el rendimiento del modelo seleccionado mediante la optimización de sus hiperparámetros. Para ello, se espera que implementen `Optuna` para optimizar no solo los hiperparámetros del modelo, sino también los de los preprocesadores utilizados (por ejemplo, OneHot Encoding, Scalers, etc.).

Al desarrollar este proceso, deberán responder las siguientes preguntas clave como mínimo:

- ¿Qué métrica decidieron optimizar y por qué?

- ¿Qué hiperparámetro tuvo un mayor impacto en el rendimiento de su modelo?

- ¿Cuánto mejoró el rendimiento del modelo después de la optimización de hiperparámetros?

In [ ]:
# Desarrolle aquí su código

## 📌 Interpretabilidad [1.0 puntos]

En esta sección, deben explicar el funcionamiento de su modelo utilizando las técnicas de interpretabilidad vistas en clase, como `SHAP`. Se espera que sean capaces de descomponer las predicciones y evaluar la importancia de los atributos y las interacciones entre ellos, con el fin de obtener una comprensión más profunda de cómo el modelo toma decisiones. 

Al desarrollar esta parte, deberán responder las siguientes preguntas clave como mínimo:

- ¿Podría explicar el funcionamiento de su modelo para una predicción en particular? Si es así, proporcione al menos tres ejemplos específicos, describiendo cómo el modelo llegó a sus decisiones y qué factores fueron más relevantes en cada caso.

- ¿Qué atributo tiene una mayor importancia en la salida de su modelo? Analice si esto tiene sentido con el problema planteado y justifique la relevancia de dicho atributo en el contexto de las predicciones que se realizan.

- ¿Existe alguna interacción entre atributos que sea relevante para el modelo? Investigue si la combinación de ciertos atributos tiene un impacto significativo en las predicciones y explíquela en **detalle**.

- ¿Podría existir sesgo hacia algún atributo en particular? Reflexione sobre la posibilidad de que el modelo esté favoreciendo ciertos atributos. Si es así, ¿cuál podría ser la causa y qué impacto podría tener esto en la predicción?

In [ ]:
# Desarrolle aquí su código

## 📌 Resultados y Conclusiones [1.0 puntos]

Para finalizar, se deben explicar los desarrollos y resultados obtenidos a lo largo de todo el proceso, desde la selección de las variables hasta la optimización de hiperparámetros e interpretación. Se espera una reflexión crítica sobre el desempeño de los modelos entrenados y una comparación entre los diferentes enfoques. Además, deberán abordar los siguientes puntos clave:

- **Análisis de métricas**: Comenten sobre las métricas obtenidas en cada etapa del modelo, destacando las más relevantes como precisión, recall, F1-score, etc. ¿Cuáles fueron los modelos más efectivos? ¿Qué diferencias notables encontró entre ellos?

- **Impacto de las decisiones tomadas**: Reflexionen sobre cómo las decisiones relacionadas con el preprocesamiento, selección de atributos y optimización de hiperparámetros influyeron en los resultados finales. ¿Hubo alguna decisión que haya tenido un impacto notable en el rendimiento?

- **Lecciones aprendidas**: Concluyan sobre las lecciones más importantes que aprendieron durante el proceso y cómo estas pueden influir en futuras iteraciones del modelo. ¿Qué se podría mejorar si se repitiera el proceso? Si tuvieran más recursos y tiempo, ¿qué otras técnicas/herramientas habrían utilizado?

> [Escriba aquí sus resultados]

Mucho éxito!

<center>
<img src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExaHpvOTY5Z3hpdHI3aDBpdGRueXRqamZncXp2emFrbjJ5M2s5eTR1dSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/1PMVNNKVIL8Ig/giphy.gif" width="300" height="200">